#include <TORICA_MoveAve.h>
#include <TORICA_MoveMedian.h>

// 対気速度
TORICA_MoveAve<5> filtered_airspeed_ms(0);
// 現在の気圧高度(気圧基準)
TORICA_MoveAve<5> filtered_air_bmp_altitude_m(0);
TORICA_MoveAve<5> filtered_under_bmp_altitude_m(0);
// プラホの高度(気圧基準)
TORICA_MoveAve<50> air_bmp_altitude_platform_m(0);
TORICA_MoveAve<50> under_bmp_altitude_platform_m(0);
// 気圧センサを用いた信頼できる対地高度
// 3つの気圧高度にそれぞれ移動平均をとってプラホを10mとし，中央値をとった値
#include <QuickStats.h>
float bmp_altitude_lake_array_m[3];
QuickStats bmp_altitude_lake_m;
// 超音波高度(対地高度)
TORICA_MoveAve<3> filtered_under_urm_altitude_m(0);
// 気圧での対地高度と超音波での対地高度の差
TORICA_MoveMedian<400> altitude_bmp_urm_offset_m(0);
